spring:
  application:
    name: itoken-admin
server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  profiles: dev
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod
  zipkin:
    base-url: http://192.168.79.135:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.79.135:8761/eureka/
