spring:
  application:
    name: itoken-zuul

server:
  port: 8769


zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: SPRINGCLOUD-WEB-ADMIN-RIBBON
    api-b:
      path: /api/b/**
      serviceId: SPRINGCLOUD-WEB-ADMIN-FEIGN
---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.79.135:8761/eureka/
