spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/suiboce/itoken-config.git
          search-paths: respo
          username: www5978058
          password: zxc5aiqi
  profiles:
    active: dev

server:
  port: 8888

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.79.129:8761/eureka/
